### ISSUE TITLE
2.1 update missing. Raiden Shogun, Kujou Sara, Engulfing LIghtning, The Catch

### ISSUE THREAD

**Issue by GabrielLV** [xanthics/genshin_grind_planner#16]
Hello. The new update 2.1 was released and the new things are currently missing from the application. The items missing are as follow

**Characters:** Raiden Shogun, Kujou Sara and Aloy

**Weapons:** Engulfing Lightning, The Catch and Predator

**Character Ascension Materials:** Dew of Repudiation and Storm Beads 

**Talent Level-up Materials:** Molten Moment, Hellfire Butterfly and Ashen Heart.

**Comment by xanthics** [comment]
I'd started to work on that (even updated the todo list) but got to here and got distracted by the new pathfinder game.  I'll see how long it takes me to get through the remaining quests to unlock the new trounce/etc so I can do a proper update with graphics

![image](https://user-images.githubusercontent.com/3137623/132117122-f6239f40-636d-4bf9-96d9-345590c99fee.png)

**Comment by xanthics** [comment]
Update.  There is an overwhelming amount of work I need to do in game to push a proper update.  I stopped playing the game because I no longer enjoy it[1].  If someone else wants to take over the site, I'll send you the tools I use and provide basic documentations and troubleshooting about how to do updates.

1) to be transparent, this site was entirely a fan project.  I have not received any donations or advertising for it, and even if that changed I am no longer interested in maintaining.

**Comment by GabrielLV** [comment]
That is completely fair and understandable. I just followed the instruction on the site to create a bug report if anything was missing.

I'm aware this is a fan project, and understand that whatever final decision is up to you. It has helped me a lot while grinding and I thank you for that.

Hope you find success in whatever endeavor you may be taking at the moment.
